
 [[book]]
title = "Reverend Insanity"
alt_titles = ["Gu Daoist Master", "蛊真人"]
thumbnail = "https://cdn.novelupdates.com/images/2025/06/Reverend-Insanity.jpg"
quality = "Peak"
reading = "Finished available, C2334"
authors = ["gu-zhen-ren"]
links = [
    { title = "novelupdates", url = "https://www.novelupdates.com/series/reverend-insanity/" },
]
