title = "Alwaldend"
theme = ["github.com/google/docsy"]
baseURL = "http://127.0.0.1:1313"
# refLinksErrorLevel = "WARNING"

enableRobotsTXT = true

[outputs]
section = ["html", "rss", "print"]
home = ["html"]
page = ["html", "rss", "print"]

[frontmatter]
lastmod = [":fileModTime"]

[sitemap]
changefreq = "daily"
priority = 0.5

[params]
offlineSearch = true
github_project_repo = "https://github.com/alwaldend/src"
github_repo = "https://github.com/alwaldend/src"
github_branch = "master"
version_menu = "Versions"
version_menu_pagelinks = true

[[params.alwaldend.links]]
name = "Docs"
url = "https://alwaldend.github.io/src/docs/"

[[params.alwaldend.links]]
name = "GitHub"
url = "https://github.com/alwaldend/"

# [params.copyright]
# authors = ""

[params.ui]
navbar_logo = false
generated_tags = ["Generated"]
separate_page_tags = ["Bzl-Targets", "Changelog"]
showLightDarkModeMenu = true
sidebar_menu_compact = true
sidebar_menu_foldable = true

[params.drawio]
enable = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
title = true

[taxonomies]
category = "categories"
language = "languages"
status = "statuses"
tag = "tags"

[[menus.main]]
name = "Docs"
weight = 100
url = "/docs/"

[security.exec]
# allow = [".*"]
# osEnv = [".*"]
# osEnv = [
#     # '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$',
#     '(?i)^(BAZEL_.+)$',
# ] # extra env for postcss

[security.funcs]
# getenv = [".*"]

[module.hugoVersion]
extended = true
min = "0.146.0"
