users_regular: {}
users_remove: {}
users_admins:
  ansible:
    name: ansible
    disable_passwd: true
    sudo_no_passwd: true
users_ssh_keys:
  ansible_1:
    user: ansible
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH/cuGf5OCGPYCoGwHwlPBf4ErPU4WrgYUXbRT6QBZNl
