- name: Setup hosts
  hosts: k3s_cluster
  force_handlers: true
  become: true
  roles:
    - role: alwaldend.main.host

- name: Setup pies
  hosts: pies
  force_handlers: true
  become: true
  roles:
    - role: alwaldend.main.raspberry_pi

- name: Setup k3s
  hosts: k3s_cluster
  force_handlers: true
  become: true
  roles:
    - role: alwaldend.main.k3s
