apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.cl1.residential.dc.alwaldend.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.cl1.residential.dc.alwaldend.com`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-ingress-certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ingress-certificate
spec:
  secretName: argocd-ingress-certificate
  dnsNames:
    - argocd.cl1.residential.dc.alwaldend.com
  issuerRef:
    name: acme
    kind: ClusterIssuer
---
