apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - network-policy.yaml
  - install.yaml
  - ingress.yaml
images:
- name: public.ecr.aws/docker/library/redis
  newName: docker.io/library/redis
